### ISSUE TITLE
can't delete an image

### ISSUE THREAD

**Issue by LuisBL** [mayflower/docker-ls#17]
I don't succeed to delete  an image

 Get tags::

    $ docker run -it docker-ls docker-ls tags --registry http://docker.corp.com proj-prod/proj_mix-app
    requesting list . done
    repository: proj-prod/proj_mix-app
    tags:
    - latest
    $

Get tag::

    $ docker run -it docker-ls docker-ls tag --registry http://docker.corp.com proj-prod/proj_mix-app:latest
    requesting manifest . done
    repository: proj-prod/proj_mix-app
    tagName: latest
    digest: sha256:dabcbeaebfb1b230476e064e5e9ee8cb4f09c3b839cde9336e5462b205744f8f
    layers:
    - sha256:4e6d082eb9bac6200504f37b1899dde47e14b668ef958ac6fdcd4faaa15eca0c
    - sha256:1d90a4de5d4e86a91d02da42bd8dd98d41b875f4d4a8549bd213318b33f9b0fa
    - sha256:0803109b66d66d3324bbd943d9824674fa5cce3ab8dd5b47c1301ce2f75de9ab
    - sha256:...
    - sha256:469ff7b80a96f039346871094fa359fc3c7a31e13ac317fa47fb96fa7155e8fb
    - sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    - sha256:43c265008fae5d1f3cbee0dac9697235320b174d85acbed002a4fe44236adec0
    (venv)luis@spinoza:~/lab/sandbox/docker-ls$ 

from the above I get the `dabcbeaebfb1b230476e064e5e9ee8cb4f09c3b839cde9336e5462b205744f8f` but Delete does not work on my side::

    $ docker run -it docker-ls docker-rm --registry http://docker.corp.com proj_mix-app:sha256:dabcbeaebfb1b230476e064e5e9ee8cb4f09c3b839cde9336e5462b205744f8f
    ERROR: invalid API response status 301
    $

the registry has a true value for `REGISTRY_STORAGE_DELETE_ENABLED` is set to true::
```
# cat docker-compose.yml 
version: '2'
services:
  docker-registry:
    container_name: docker-registry
    image: registry:2
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - docker-registry-volume:/var/lib/registry
      - /root/docker.corp.com/registry/docker.corp.com.auth:/auth
 
volumes:
  docker-registry-volume:
    driver: local
```
